# Generated by Django 5.1.3 on 2025-09-03 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('guest_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_subscriber', to=settings.AUTH_USER_MODEL)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_subscribed', to='rooms.hotel')),
            ],
            options={
                'verbose_name': 'Hotel Subscriber',
                'verbose_name_plural': 'Hotel Subscribers',
            },
        ),
    ]
