# Generated by Django 5.1.3 on 2025-08-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_avg_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='avg_price',
            new_name='budget',
        ),
    ]
