# Generated by Django 5.1.3 on 2025-08-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='budget',
            new_name='avg_price',
        ),
    ]
