# Generated by Django 5.1.3 on 2025-08-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_budget_customuser_avg_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avg_price',
        ),
    ]
