# Generated by Django 5.1.3 on 2025-08-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
