# Generated by Django 5.1.3 on 2025-08-27 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecommendation',
        ),
    ]
