# Generated by Django 5.1.3 on 2025-08-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_userrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='budget',
        ),
    ]
