# Generated by Django 5.1.3 on 2025-09-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='fb_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='in_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tw_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
