# Generated by Django 5.1.3 on 2025-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitesettings', '0002_alter_settings_fb_link_alter_settings_in_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
